[package]
name = "lotl-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
lotl-token = { workspace = true }
lotl-ast = { workspace = true }
lotl-error = { workspace = true }
uuid = { version = "1.18.1", features = ["v4"] }

[dev-dependencies]
lotl-lexer = { workspace = true }